---
layout: cv
title: Dylan Kohn's CV
---
# Dylan Kohn
Mobile: (925) 822-5916 | dylankohn1@gmail.com  
[linkedin.com/in/dylantkohn](https://linkedin.com/in/dylantkohn)

## Summary
Computer programmer and software engineer with 10 years of programming experience, constantly learning and improving with a growth mindset. Currently a student at BYU-Idaho studying computer science with an emphasis on machine learning. Exploring a career path in machine learning and embedded systems. Passionate about creating efficient and user-friendly software solutions.

## Skills
- Python, C#, R, HTML, CSS, JavaScript, SQL  
- Git collaboration & teamwork  
- API integration & external sources  
- Fluent in Spanish  
- Full-stack application development  
- Knowledge of BigQuery, PowerBi, and GA4  

## Education
**Bachelor of Science - Computer Science**  
Brigham Young University - Idaho  
2022 - 2026 (estimated) | Rexburg, Idaho  

## Service Mission
**Church of Jesus Christ of Latter-Day Saints**  
2022 - 2024 | Vancouver, Washington  
- Learned Spanish to teach native speakers  
- Taught English classes  
- Shared religious principles  

## Work Experience
**Web Analytics Integration Programmer**  
BYU-Idaho  
- Data Analyst for BYU-Idaho website  
- Use of SQL and BigQuery for data manipulation  
- Google Ads and other Ad campaigns management  

**Company Management Application**  
DeHaro Construction  
- Full-stack app to track company assets  
- Implemented data security through hashing and encryption  
- Displayed data in one place for ease of access and dynamic manipulation  

**QuickBite Hackathon Webapp**  
BYU-Idaho Hackathon  
- Front-end clean UI & back-end API call  
- 1st place for best UI design  
- Worked in a team of three to produce app in 24 hours  

**Programming with Functions Teachers Assistant**  
BYU-Idaho Faculty  
- Worked with students to develop Python skills  
- Worked with professor to develop course material  